### ISSUE TITLE
move XSD2SCH here

### ISSUE THREAD

**Issue by gimsieke** [Schematron/awesome-schematron#2]
…or into a different repo of this Github user.

In addition, there should be a meaningful redirect for the http://www.schematron.com/resource/XSD2SCH.zip package that is mentioned in http://broadcast.oreilly.com/2009/03/post-1.html and https://lists.w3.org/Archives/Public/xmlschema-dev/2009Mar/0000.html

Thanks!

**Comment by tgraham-antenna** [comment]
The `xsd2sch` code is currently in Schematron/schematron.

See Schematron/schematron#32 for the issue about making `xsd2sch` into a separate repository.

You'll have to bring the schematron.com link to Rick's attention.

**Comment by gimsieke** [comment]
Ah, thanks for the info, Tony. My primary concern was that it wouldn’t get lost, which it obviously didn’t. The secondary concern was about the dangling links to schematron.com. I was somehow hoping that Rick reads the issues here; I don’t have his contact details.

**Comment by rjelliffe** [comment]
Sorry, I looked at the issue for the schematron/schematron not this issue list.  

I have added the link to here (github) on the schematron.com   404  page. That should help people following old links looking for code and scripts.

**Comment by tgraham-antenna** [comment]
I think that we've agreed that `xsd2sch` hasn't been lost.
